In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
car_df = pd.read_csv('/kaggle/input/car-purchasing-dataset/Car_Purchasing_Data.csv', encoding='ISO-8859-1')
car_df.replace([np.inf, -np.inf], np.nan, inplace=True)


In [3]:
car_df

Customer Name                                    Customer e-mail  \
0      Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu   
1      Harlan Barnes                                eu.dolor@diam.co.uk   
2    Naomi Rodriquez  vulputate.mauris.sagittis@ametconsectetueradip...   
3    Jade Cunningham                            malesuada@dignissim.com   
4       Cedric Leach     felis.ullamcorper.viverra@egetmollislectus.net   
..               ...                                                ...   
495           Walter                                ligula@Cumsociis.ca   
496            Vanna                 Cum.sociis.natoque@Sedmolestie.edu   
497            Pearl                      penatibus.et@massanonante.com   
498             Nell                  Quisque.varius@arcuVivamussit.net   
499            Marla                          Camaron.marla@hotmail.com   

          Country  Gender        Age  Annual Salary  Credit Card Debt  \
0        Bulgaria       0  41.851720    62812.09301      11609.380910   
1          Belize       0  40.870623    66646.89292       9572.957136   
2         Algeria       1  43.152897    53798.55112      11160.355060   
3    Cook Islands       1  58.271369    79370.03798      14426.164850   
4          Brazil       1  57.313749    59729.15130       5358.712177   
..            ...     ...        ...            ...               ...   
495         Nepal       0  41.462515    71942.40291       6995.902524   
496      Zimbabwe       1  37.642000    56039.49793      12301.456790   
497   Philippines       1  53.943497    68888.77805      10611.606860   
498      Botswana       1  59.160509    49811.99062      14013.034510   
499        marlal       1  46.731152    61370.67766       9391.341628   

       Net Worth  Car Purchase Amount  
0    238961.2505          35321.45877  
1    530973.9078          45115.52566  
2    638467.1773          42925.70921  
3    548599.0524          67422.36313  
4    560304.0671          55915.46248  
..           ...                  ...  
495  541670.1016          48901.44342  
496  360419.0988          31491.41457  
497  764531.3203          64147.28888  
498  337826.6382          45442.15353  
499  462946.4924          45107.22566  

[500 rows x 9 columns]

In [4]:
car_df.head(5)

Customer Name                                    Customer e-mail  \
0    Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu   
1    Harlan Barnes                                eu.dolor@diam.co.uk   
2  Naomi Rodriquez  vulputate.mauris.sagittis@ametconsectetueradip...   
3  Jade Cunningham                            malesuada@dignissim.com   
4     Cedric Leach     felis.ullamcorper.viverra@egetmollislectus.net   

        Country  Gender        Age  Annual Salary  Credit Card Debt  \
0      Bulgaria       0  41.851720    62812.09301      11609.380910   
1        Belize       0  40.870623    66646.89292       9572.957136   
2       Algeria       1  43.152897    53798.55112      11160.355060   
3  Cook Islands       1  58.271369    79370.03798      14426.164850   
4        Brazil       1  57.313749    59729.15130       5358.712177   

     Net Worth  Car Purchase Amount  
0  238961.2505          35321.45877  
1  530973.9078          45115.52566  
2  638467.1773          42925.70921  
3  548599.0524          67422.36313  
4  560304.0671          55915.46248

In [5]:
X=car_df.drop(['Customer Name', 'Customer e-mail', 'Country', 'Car Purchase Amount'],axis=1)

In [6]:
X

Gender        Age  Annual Salary  Credit Card Debt    Net Worth
0         0  41.851720    62812.09301      11609.380910  238961.2505
1         0  40.870623    66646.89292       9572.957136  530973.9078
2         1  43.152897    53798.55112      11160.355060  638467.1773
3         1  58.271369    79370.03798      14426.164850  548599.0524
4         1  57.313749    59729.15130       5358.712177  560304.0671
..      ...        ...            ...               ...          ...
495       0  41.462515    71942.40291       6995.902524  541670.1016
496       1  37.642000    56039.49793      12301.456790  360419.0988
497       1  53.943497    68888.77805      10611.606860  764531.3203
498       1  59.160509    49811.99062      14013.034510  337826.6382
499       1  46.731152    61370.67766       9391.341628  462946.4924

[500 rows x 5 columns]

In [7]:
y=car_df['Car Purchase Amount']

In [8]:
y

0      35321.45877
1      45115.52566
2      42925.70921
3      67422.36313
4      55915.46248
          ...     
495    48901.44342
496    31491.41457
497    64147.28888
498    45442.15353
499    45107.22566
Name: Car Purchase Amount, Length: 500, dtype: float64

In [9]:
X.shape

(500, 5)

In [10]:
y.shape

(500,)

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [12]:
X_scaled.shape

(500, 5)

In [13]:
scaler.data_max_

array([1.e+00, 7.e+01, 1.e+05, 2.e+04, 1.e+06])

In [14]:
scaler.data_min_

array([    0.,    20., 20000.,   100., 20000.])

In [15]:
y=y.values.reshape(-1,1)

In [16]:
y_scaled = scaler.fit_transform(y)

In [17]:
y_scaled

array([[0.37072477],
       [0.50866938],
       [0.47782689],
       [0.82285018],
       [0.66078116],
       [0.67059152],
       [0.28064374],
       [0.54133778],
       [0.54948752],
       [0.4111198 ],
       [0.70486638],
       [0.46885649],
       [0.27746526],
       [0.56702642],
       [0.57056385],
       [0.61996151],
       [0.46217916],
       [0.49157341],
       [0.50188722],
       [0.64545808],
       [0.59339372],
       [0.48453965],
       [0.53860366],
       [0.53007738],
       [0.50814651],
       [0.49841668],
       [0.3966416 ],
       [0.56467566],
       [0.6950749 ],
       [0.49287831],
       [0.12090943],
       [0.50211776],
       [0.80794216],
       [0.62661214],
       [0.43394857],
       [0.60017103],
       [0.42223485],
       [0.01538345],
       [0.37927499],
       [0.64539707],
       [0.51838974],
       [0.45869677],
       [0.26804521],
       [0.2650104 ],
       [0.84054134],
       [0.84401542],
       [0.35515157],
       [0.406

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled,test_size = 0.30)

In [19]:
X_train.shape

(350, 5)

In [20]:
X_test.shape

(150, 5)

In [21]:
import tensorflow.keras
from keras.models import Sequential 
from keras.layers import Dense

model = Sequential()
model.add(Dense(25, input_dim = 5, activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1, activation='linear'))

2024-02-07 15:02:07.892471: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-07 15:02:07.892585: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-07 15:02:08.019911: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 25)                150       
                                                                 
 dense_1 (Dense)             (None, 25)                650       
                                                                 
 dense_2 (Dense)             (None, 1)                 26        
                                                                 
Total params: 826 (3.23 KB)
Trainable params: 826 (3.23 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [24]:
epochs_hist=model.fit(X_train,y_train, epochs=100, batch_size=75, verbose=1, validation_split=0.2)

Epoch 1/100
4/4 [==============================] - 1s 62ms/step - loss: 0.3657 - val_loss: 0.3171
Epoch 2/100
4/4 [==============================] - 0s 10ms/step - loss: 0.2639 - val_loss: 0.2290
Epoch 3/100
4/4 [==============================] - 0s 9ms/step - loss: 0.1874 - val_loss: 0.1610
Epoch 4/100
4/4 [==============================] - 0s 9ms/step - loss: 0.1291 - val_loss: 0.1089
Epoch 5/100
4/4 [==============================] - 0s 10ms/step - loss: 0.0849 - val_loss: 0.0705
Epoch 6/100
4/4 [==============================] - 0s 10ms/step - loss: 0.0542 - val_loss: 0.0441
Epoch 7/100
4/4 [==============================] - 0s 16ms/step - loss: 0.0336 - val_loss: 0.0283
Epoch 8/100
4/4 [==============================] - 0s 10ms/step - loss: 0.0225 - val_loss: 0.0213
Epoch 9/100
4/4 [==============================] - 0s 9ms/step - loss: 0.0187 - val_loss: 0.0198
Epoch 10/100
4/4 [==============================] - 0s 9ms/step - loss: 0.0191 - val_loss: 0.0200
Epoch 11/100
4/4 [=====